/*
  # Create ml_training_data table for pre-training ML model

  This table stores the dummy/simulated solar panel dataset used for
  pre-training the predictive model (Transfer Learning Phase 1).
  Real sensor data stays in the existing `sensor_data` table.

  Columns mirror the local Excel dataset exactly.
*/

CREATE TABLE IF NOT EXISTS ml_training_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ,
  date DATE,
  hour INTEGER,
  month INTEGER,
  season TEXT,
  solar_irradiance_w_m2 NUMERIC NOT NULL DEFAULT 0,
  cloud_cover_pct NUMERIC NOT NULL DEFAULT 0,
  ambient_temperature_c NUMERIC NOT NULL DEFAULT 0,
  panel_temperature_c NUMERIC NOT NULL DEFAULT 0,
  wind_speed_m_s NUMERIC NOT NULL DEFAULT 0,
  humidity_pct NUMERIC NOT NULL DEFAULT 0,
  voltage_v NUMERIC NOT NULL DEFAULT 0,
  current_a NUMERIC NOT NULL DEFAULT 0,
  power_output_kw NUMERIC NOT NULL DEFAULT 0,
  energy_kwh NUMERIC NOT NULL DEFAULT 0,
  saving_inr NUMERIC NOT NULL DEFAULT 0,
  household_demand_kw NUMERIC NOT NULL DEFAULT 0,
  grid_import_kw NUMERIC NOT NULL DEFAULT 0,
  grid_export_kw NUMERIC NOT NULL DEFAULT 0,
  self_sufficiency_pct NUMERIC NOT NULL DEFAULT 0
);

-- Enable Row Level Security
ALTER TABLE ml_training_data ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for ML model training scripts)
DROP POLICY IF EXISTS "Allow public read access to training data" ON ml_training_data;
CREATE POLICY "Allow public read access to training data"
  ON ml_training_data
  FOR SELECT
  USING (true);

-- Allow authenticated users to insert training data
DROP POLICY IF EXISTS "Allow authenticated users to insert training data" ON ml_training_data;
CREATE POLICY "Allow authenticated users to insert training data"
  ON ml_training_data
  FOR INSERT
  WITH CHECK (true);
